version: '3.9'

services:
    redis:
        restart: unless-stopped
        image: redis:7.0.0-alpine3.15
        volumes:
            - ../data/redis/:/data/
        ports:
            - "6379:6379"

    celery:
        build: .
        env_file:
            - .env
        entrypoint: celery -A orders worker
        depends_on:
            - redis
        volumes:
            - .:/app
