# Generated by Django 3.2.16 on 2022-12-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20221224_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='contact',
            new_name='contact_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_info',
            new_name='product_info_id',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
