# Generated by Django 3.2.16 on 2022-12-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20221227_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.AlterField(
            model_name='contact',
            name='house',
            field=models.CharField(max_length=15, verbose_name='Дом'),
        ),
    ]
