# Generated by Django 3.2.16 on 2023-01-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20230109_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
