# Generated by Django 3.2.16 on 2023-01-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_user_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfirmEmailToken',
        ),
    ]
