# Generated by Django 3.2.16 on 2023-01-16 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_delete_confirmemailtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='state',
        ),
    ]
