# Generated by Django 3.2.16 on 2023-01-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_product_is_active'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productinfo',
            name='unique_product_info',
        ),
        migrations.AddConstraint(
            model_name='productinfo',
            constraint=models.UniqueConstraint(fields=('product_id', 'shop_id', 'external_id', 'is_active'), name='unique_product_info'),
        ),
    ]
