# Generated by Django 3.2.16 on 2023-01-17 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20230116_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='backend.contact', verbose_name='Контакт'),
        ),
    ]
