# Generated by Django 3.2.16 on 2023-01-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_order_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='house',
            field=models.CharField(blank=True, max_length=15, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='street',
            field=models.CharField(blank=True, max_length=100, verbose_name='Улица'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('city', ''), _negated=True), models.Q(('street', ''), _negated=True), models.Q(('house', ''), _negated=True)), ('phone__isnull', False), _connector='OR'), name='phone_or_address_reqiured'),
        ),
    ]
