# Generated by Django 3.2.16 on 2023-01-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20230117_0257'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='phone_or_address_reqiured',
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('city', ''), _negated=True), models.Q(('street', ''), _negated=True), models.Q(('house', ''), _negated=True)), models.Q(('phone', ''), _negated=True), _connector='OR'), name='phone_or_address_reqiured'),
        ),
    ]
